-- Demo/test seed data moved to supabase/seed.sql
-- This migration previously inserted test organization and membership data,
-- which has been relocated to seed.sql to avoid FK constraint issues during migration.
